ArkEcosystem/cpp-crypto

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Added github issue and PR templates
FIles pulled from https://github.com/ArkEcosystem/boilerplate
Fixes #3

chore: Add github templates

---

.travis.yml
cmake/CodeCoverage.cmake
test/CMakeLists.txt
test/transactions/deserializer.cpp
travis/script_desktop.sh

Added support for Travis CI to run code coverage
and upload the report to CodeCov.
- [X ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
FIxes #2

feat: add codecov support

---

src/CMakeLists.txt
src/helpers/helpers.cpp

Added stub setup and loop functions to fix linker error on Arduino builds of static library.
Fixes #14

chore: Add stub setup and loop functions

---

.codecov.yml

Add a Codecov config file to ignore tests when calculating code coverage.  There is IoT test code that is not executed on desktops and skews the coverage numbers.
Also excluded git submodules from coverage.
N/A

chore: Add Codecov config file

---

platformio.ini
test/platformio.ini

Corrected typo in PIO config files
N/A

chore:  Correct typo

---

.circleci/clang_format.sh
.circleci/config.yml
.clang_format

Added support for running clang format in CI.  clang format warnings will not error the build (yet?)
N/A

chore: add clang format support

---

.appveyor.yml
CHANGELOG.md

This PR adds the `.appveyor.yml` configuration file and updates the change log.
It is [WIP] until #83 is merged as Appveyor tests will fail.

[WIP]test: Add Appveyor CI Support

---

library.json

This PR updates the dependencies list in the library.json manifest.
Just helps keep the manifests stay consistent across branches and repos.
It shouldn't really affect much, otherwise.
~- [ ] New/updated tests are included~ n/a

chore(manifest): add supported platforms arduino

---

library.json

This PR updates the dependencies list in the library.json manifest.
This should merge okay with #107
Just helps keep the manifests stay consistent across branches and repos.
It shouldn't really affect much, otherwise.
~- [ ] New/updated tests are included~ n/a

chore(manifest): update dependencies

---

src/identities/address.cpp
src/include/cpp-crypto/transactions/builder.h
src/include/cpp-crypto/transactions/transaction.h
src/transactions/builder.cpp
src/transactions/deserializer.cpp
src/transactions/serializer.cpp
src/transactions/transaction.cpp
test/transactions/builder.cpp
test/transactions/deserializer.cpp
test/transactions/serializer.cpp
test/transactions/transaction.cpp

This PR updates transaction json values to match Core 2.5.
- transaction `amount` Json as string.
- transaction `fee` Json as string.
- updates tests to match changes.
- cleanup transaction tests.

chore(transaction): update amounts json

---

CHANGELOG.md
README.md

This PR updates the changelog and  merges `master` #93 to `develop`.
No idea how 93 slipped through 🤷‍♂ 

chore: update changelog and merge #93 from master

---

.github/workflows/test/script_arduino.sh
platformio.ini
test/platformio.ini

This PR changes the PIO configs to use explicit package version.

chore(pio): use explicit package versions

---

test/iot/platform.hpp
test/iot/test_main.cpp
test/platformio.ini

* Disabled WiFi  radio during tests to lower current  draw.
* Increased CPU frequency to execute tests faster to improve
stability.  Stability has been improved but is not perfect.  There is
~15% failure rate when running complex tests where the board
goes through a DMT reset.
Improves #179

feat: disable wifi on esp8266 during tests

---

src/crypto/message.cpp
src/crypto/slot.cpp
src/lib/rfc6979/rfc6979.h
src/utils/hex.hpp
src/utils/str.hpp

Moved global const data to function local to reduce
global memory footprint on embedded platforms.

chore: move global data to function local

---

CHANGELOG.md

- Separate Changelogs by platform.
eg
`tree/master`
- \#\# [1.0.0] - 2020-02-13
`tree/arduino`
- \#\# [1.0.0-arduino] - 2020-02-13

docs(changelog): separate platforms [arduino]

---

CHANGELOG.md
src/transactions/builders/builder.hpp
src/transactions/builders/delegate_resignation.hpp

- add Delegate Resignation Builder file to `/builders/` dir.
- add Delegate Resignation header include to `builder.hpp`.
- update the CHANGELOG.

chore(transactions): add delegate resignation builder [arduino]

---

.codacy.yml
.github/workflows/test/clang_format.sh
build.sh
run_tests.sh
src/include/cpp-crypto/interfaces/constants.h
src/transactions/mapping/labels.hpp
src/transactions/types/delegate_registration.cpp
src/transactions/types/htlc_claim.cpp
src/transactions/types/htlc_lock.cpp
src/transactions/types/htlc_refund.cpp
src/transactions/types/ipfs.cpp
src/transactions/types/multi_payment.cpp
src/transactions/types/second_signature.cpp
src/transactions/types/transfer.cpp
src/transactions/types/vote.cpp
test/iot/platform.hpp
test/test_helpers.h
test/transactions/builders/transfer.cpp

Various CI improvements per Codacy & CodeFactor
- rm `codacy.yml` config file.
- not used by repo/org, configuration allowed via codacy dashboard.
- update all `.sh` files to use the `#!/usr/bin/env bash` shebang.
- use correct print flag for size_t in test helper method.
- remove unused local in unit test.
- rm duplicate empty line in `test/iot/platform` file.
- use explicit size vs strlen for transaction labels (mapping, json).
These are non-breaking changes.

ci: maintenance

---

CHANGELOG.md
examples/ESP32/ESP32.ino
examples/ESP8266/ESP8266.ino
src/common/configuration.hpp
src/transactions/builders/common.hpp
src/transactions/builders/delegate_registration.hpp
src/transactions/builders/delegate_resignation.hpp
src/transactions/builders/htlc_claim.hpp
src/transactions/builders/htlc_lock.hpp
src/transactions/builders/htlc_refund.hpp
src/transactions/builders/ipfs.hpp
src/transactions/builders/multi_payment.hpp
src/transactions/builders/second_signature.hpp
src/transactions/builders/transfer.hpp
src/transactions/builders/vote.hpp

- move `Configuration` argument to initial builder constructor.
- enable passing `Configuration` arguments to the builder constructor.
- update the CHANGELOG.

chore(builder): improvements [arduino]

---

extras/ARDUINO_IDE.sh

- use double quotes
- use printf
- fix typos

chore: improve ARDUINO_IDE.sh script [arduino]

---

extras/ARDUINO_IDE.sh

- use double quotes
- use printf
- fix typos

chore: improve ARDUINO_IDE.sh script
