ArkEcosystem/cpp-crypto

- .circleci/install_platform_io.sh
- platformio.ini
- test/platformio.ini
Updated BIP39 submodule and PIO configs to be more explicit in determining dependencies.  This allows for more control and better determinism as to what PIO will actually compile into the project.
This should fix the current build issues in the open PRs.
> fix:  Correct PIO builds

- platformio.ini
This change fixes the currently broken PIO CI builds by correcting the submodules ignore paths in the PIO INI file.
N/A
> Fix PIO CI Builds

- CHANGELOG.md
- src/transactions/transaction.cpp
- src/utils/message.cpp
Current Windows builds fail with the following:
`error C2131: expression did not evaluate to a constant`
> example build log can be found here: [FAILING: ci.appveyor/sleepdefic1t/cpp-crypto](https://ci.appveyor.com/project/sleepdefic1t/cpp-crypto/builds/24682089/job/kx9dyho0p961m0sf)
This is due to the way Windows handles dynamic allocation.
The current implementation uses this breaking allocation pattern in `transaction.cpp` and `message.cpp`.
After the changes in this PR, Windows builds pass.
> example build log can be found here: [PASSING: ci.appveyor/sleepdefic1t/cpp-crypto](https://ci.appveyor.com/project/sleepdefic1t/cpp-crypto/builds/24682137/job/5b40uk1h4pat3x00)
A later PR will address adding Appveyor support.
> fix: improve Windows support.

- CHANGELOG.md
- test/platformio.ini
AUnit has stopped correctly building tests for the partially-supported ESP8266 platform on Linux platforms.
It seems this may be a change in either PIO, AUnit, or ESP8266 Core; so this PR disables ESP8266 tests in PlatformIO until support is worked out.
This points PIO CI testing to the fully supported ESP32 platform instead.
Disables ESP8266 test building on PlatformIO
> misc: Disable PlatformIO ESP8266 Tests

- CHANGELOG.md
- library.json
- library.properties
- src/transactions/transaction.cpp
This PR supports the change in vendorField size from 64 bytes to 255 bytes in Core v2.4.
Specifically:
- `transaction.cpp`: update vendorField handling.
- minor version bump
- makes changelog current as of master + changes.
This also addresses #82
> feat: Increase VendorField Size

- CHANGELOG.md
- src/include/cpp-crypto/transactions/builder.h
- src/transactions/builder.cpp
- src/transactions/transaction.cpp
- test/transactions/builder.cpp
This PR addresses #79 and adds additional checking to ensure that a 'Type-0'/Transfer Transaction amount is greater than 0 ARKtoshi. 
This PR:
- returns empty/unvalidatable transaction if Transfer-type amount is not > 0.
- adds comments about > 0 ARKtoshi to Transaction::buildTransfer declaration.
- adds test for 0 ARKtoshi amount on Type-0 tx's.
note: 0 is already default amount for Transactions, no additional changes were needed.
> fix: 0 ARKtoshi amount handling

- keywords.txt
The Arduino IDE requires the use of a single true tab separator between the keyword name and identifier. When spaces are used rather than a true tab, the keyword is not highlighted.
Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords
- [NA] All tests are passing
- [NA] New/updated tests are included
If adding a **new feature**, the PR's description includes:
- [NA] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)
> chore: use correct field separator in keywords.txt

- test/networks/abstractnetwork.cpp
Current tests are ran in different orders per platform.
This led to a global test custom_network (AbstractNetwork) being modified incorrectly.
This PR properly handles that order variation by creating a local object to be modified instead.
Tests may fail until #101 is merged and this PR is rebased.
> test(networks): Fix AbstractNetwork Tests

- CHANGELOG.md
- src/helpers/crypto_helpers.h
- src/transactions/transaction.cpp
Current implementation sometimes fails to properly serialize numbers in the `toJson()` method.
This is especially an issue in some Linux builds and all Arduino IDE builds (Arduino IDE Library Manager version (Cpp-Crypto-Arduino-v.0.3.0)).
Specifically, this PR does the following:
- moves `<cinttypes>` to `crypto_helpers.h` for non-IoT builds.
- forces type serialization for:
- `amount` (llu/uint64_t).
- `fee` (llu/uint64_t).
- `network` (uint8_t/int).
- `timestamp` (lu/uint32_t).
- `type` (uint8_t/int).
- `version` (uint8_t/int).
- updates the changelog.
This PR resolves #99.
Tests will fail until #101 is merged and this PR is rebased.
> fix(transaction): Improve Numeric Json Serialization

- library.json
As reported by @yhyuan in https://github.com/ArkEcosystem/cpp-crypto/issues/104,
the current library manifest uses a wildcard `*` for the `platforms` value signifying that it supports all platforms.
This is incorrect as the Cpp SDK's only officially support the espressif8266 & espressif32 platforms.  This PR corrects that discrepancy.
Affects external package manager library manifest
- [n/a] New/updated tests are included
> fix(manifest): Correct Supported Platforms

- src/identities/address.cpp
- src/transactions/builder.cpp
- src/transactions/builder.h
- src/transactions/deserializer.cpp
- src/transactions/serializer.cpp
- src/transactions/transaction.cpp
- src/transactions/transaction.h
This PR updates transaction json values to match Core 2.5 for the Arduino branch.
- transaction `amount` Json as string.
- transaction `fee` Json as string.
> [arduino]chore(transaction): update amounts json

- CHANGELOG.md
- README.md
This PR updates the changelog and  merges `master` #93 to `arduino`.
No idea how 93 slipped through 🤷‍♂ 
> [arduino] docs: update changelog and merge #93 from master

- CMakeSettings.json
- test/common/fee_policy.cpp
- test/helpers/crypto.cpp
- test/helpers/encoding/hex.cpp
Added back missing JSON file that integrates cmake build system into the Visual Studio IDE.
Cleared warnings.
If adding a **new feature**, the PR's description includes:
> chore: Visual Studio Support

- src/include/cpp-crypto/transactions/builder.h
- src/include/cpp-crypto/transactions/transaction.h
- src/transactions/builder.cpp
- src/transactions/transaction.cpp
- test/transactions/transaction.cpp
* Added explicit default ctors/assign for copy/move to builder
* Changed  builder sign function to return void and pass transaction in by reference to avoid copies.
* Updated transaction tests to check for version.
If adding a **new feature**, the PR's description includes:
> fix: Add missing initialization for transaction version

- src/crypto/curve.cpp
FIxed bug where an unallocated vector was being used.
Changed to use fix array since the buffer was never dynamic.
> fix(crypto): fix crash in tests

- .github/workflows/test/script_arduino.sh
This PR adjusts the Arduino CI paths for GH Actions.
> ci: update arduino triggers

- .github/workflows/test.yml
Environment variables aren't persisted between steps so they need to be set per step or globally.
> ci: pass environment variables to steps

- CMakeLists.txt
The regex call in `header-filter` doesn't work as expected.
The current behavior is identical to the default clang-tidy `-header-filter` default of `.*`.
You can see the regex not being obeyed in any of the passing "actions" or back on CircleCI.
https://github.com/ArkEcosystem/cpp-crypto/runs/244420978#step:6:1
https://github.com/ArkEcosystem/cpp-crypto/runs/242577996#step:6:1
https://circleci.com/gh/ArkEcosystem/cpp-crypto/1595
Since it doesn't work and is misleading, this PR removes that call.
CI will fail on PlatformIO builds due to not using explicit package versions.
A subsequent PR will address this issue.
> chore: remove `header-filter` clang-tidy call

- .codeclimate.yml
C++ isn't supported out of the box but requires a plugin to be configured. See https://docs.codeclimate.com/docs/cppcheck and https://github.com/antiagainst/codeclimate-cppcheck#configuration.
> ci: setup cppcheck for codeclimate

- cmake/extern/ArduinoJson.txt.in
- cmake/extern/BIP66.txt.in
- cmake/extern/GTest.txt.in
- cmake/extern/uECC.txt.in
This PR adds project-download calls to silence external package build warnings.
> fix: cmake warnings

- .github/workflows/codeclimate.yml
- .github/workflows/coverage.yml
CodeClimate Coverage apparently attempts to use the `CC_TEST_REPORTER_ID` of the PR base for reporting on the upstream parent, which fails.
This PR splits workflows so that CodeClimate Coverage onlys runs on Pushes to master/devleop.
CodeCov will continue to run on PR's and Pushes.
> ci: split coverage workflows

- .github/workflows/test.yml
Corrected syntax in call to unit test exe
> ci: call correct EXE for windows tests

- test/platformio.ini
Explicit upload port set in PIO config was left in.  This was used for debugging on my specific machine.  It should be removed.
> Remove upload port used for debugging

- .github/workflows/test/install_arduino.sh
- .github/workflows/test/script_arduino.sh
With the recent support for esp8266 added back in, it would be nice to have that in the Arduino CLI CI tests.
> ci: add esp8266 arduino cli configs back

- examples/arduino/ESP32/ESP32.ino
- examples/arduino/ESP32/arkCrypto_esp32.h
- examples/arduino/ESP8266/ESP8266.ino
- examples/arduino/ESP8266/arkCrypto_esp8266.h
- src/include/cpp-crypto/arkCrypto.h
- test/common/configuration.cpp
- test/common/fee_policy.cpp
- test/common/network.cpp
- test/defaults/static_fees.cpp
- test/defaults/transaction_types.cpp
- test/transactions/deserializer_multi_signature_registration.cpp
- test/transactions/deserializer_second_signature_registration.cpp
- test/transactions/deserializer_transfer.cpp
- test/transactions/deserializer_vote.cpp
- test/transactions/serializer.cpp
- test/transactions/transaction.cpp
- test/transactions/transaction_to_json_type_0.cpp
- test/transactions/transaction_to_json_type_1.cpp
- test/transactions/transaction_to_json_type_2.cpp
- test/transactions/transaction_to_json_type_3.cpp
* Updated arkCrypto.h header to just be a dummy header for the sole
purpose of forcing the cpp-crypto library to be linked into an
Arduino sketch.
* Updated tests to use specific headers instead of arkCrypto.h
* Updated Arduino sample sketches to use only the headers required
for the sketch.
> refactor: remove usage of monolithic arkCrypto.h

- cmake/extern/ArduinoJson.txt.in
- cmake/extern/BIP66.txt.in
- cmake/extern/GTest.txt.in
- cmake/extern/uECC.txt.in
- ignores detached head warnings when cloning external libs from CMake.
> build: hide cmake warnings

- README.md
- add [![C++11](https://badgen.net/badge/c++/11/blue?labelColor=black)](https://isocpp.org/wiki/faq/cpp11) to `README.md` badges.
> chore(docs): add c++11 badge

- src/transactions/types/htlc_claim.cpp
- fix Htlc Claim unlockSecret Json to display as a 64-char hash.
> fix(transactions): htlc claim secret [arduino]

- src/interfaces/constants.h
- src/transactions/mapping/labels.hpp
- src/transactions/types/delegate_registration.cpp
- src/transactions/types/htlc_claim.cpp
- src/transactions/types/htlc_lock.cpp
- src/transactions/types/htlc_refund.cpp
- src/transactions/types/ipfs.cpp
- src/transactions/types/multi_payment.cpp
- src/transactions/types/second_signature.cpp
- src/transactions/types/transfer.cpp
- src/transactions/types/vote.cpp
Per Codacy & CodeFactor
- use explicit size vs strlen for transaction labels (mapping, json).
This is a non-breaking change.
> chore(transactions): use explicit size vs strlen for labels [arduino]

- test/utils/str.cpp
This PR adds unit tests to ensure `UintToString` works as expected.
This also resolves CodeCov incorrectly missing `UintToString`,
even though it is used internally.
> test(utils): add missing str tests
